### ISSUE TITLE
Error on the test data

### ISSUE THREAD

**Issue by cjy8709** [JialiUMassWengLab/TEMP#11]
Hello

I was trying to run the test data using the Absence script and ran into the following error:

> Testing required softwares/scripts:
> "echo" is using: /usr/bin/echo
> "rm" is using: /usr/bin/rm
> "mkdir" is using: /usr/bin/mkdir
> "date" is using: /usr/bin/date
> "mv" is using: /usr/bin/mv
> "sort" is using: /usr/bin/sort
> "touch" is using: /usr/bin/touch
> "awk" is using: /usr/bin/awk
> "grep" is using: /usr/bin/grep
> "twoBitToFa" is using: /storage/jae.youngchoi/PROGRAMS_AND_SCRIPTS/PROGRAMS/kentUtils/bin/twoBitToFa
> "bwa" is using: /storage/jae.youngchoi/miniconda2/bin/bwa
> "samtools" is using: /storage/jae.youngchoi/miniconda2/bin/samtools
> Done with testing required softwares/scripts, starting pipeline...
> test_chromosome.sorted.bam
> test_chromosome
> Error: Type checker found wrong number of fields while tokenizing data line.

I ran with command:

> bash /storage/jae.youngchoi/PROGRAMS_AND_SCRIPTS/PROGRAMS/TEMP/scripts/TEMP_Absence.sh \\
> -i /storage/jae.youngchoi/PROGRAMS_AND_SCRIPTS/PROGRAMS/TEMP/test_dataset/test_chromosome.sorted.bam \\
> -s /storage/jae.youngchoi/PROGRAMS_AND_SCRIPTS/PROGRAMS/TEMP/scripts/ \\
> -o /storage/jae.youngchoi/PROGRAMS_AND_SCRIPTS/PROGRAMS/TEMP/test_dataset/TMP/ \\
> -r /storage/jae.youngchoi/PROGRAMS_AND_SCRIPTS/PROGRAMS/TEMP/test_dataset/test_TE_annotation.bed \\
> -t /storage/jae.youngchoi/PROGRAMS_AND_SCRIPTS/PROGRAMS/TEMP/test_dataset/dm3_chr2L.2bit \\
> -x 10

I'm using samtools v1.4.1; bwa 0.7.15-r1140; bedtools v2.26.0.
Quick google search indicates that error is from bedtools and I'm wondering if there's any suggestion for the error?

Many thanks!

Best

Jae

**Comment by JialiUMassWengLab** [comment]
Hi Jae,

Is there any way you can share the intermediate files? It's hard for me to diagnose with current information. 

Jiali

**Comment by yfu** [comment]
It appears that bedtools v2.26.0 is having problems dealing with `bedtools intersect -a test_TE_annotation.bed -b test_chromosome.unproper.uniq.interval.bed`. I tried bedtools v2.25.0 and it works find here.

Best!
Yu

**Comment by cjy8709** [comment]
Yes it was a version issue and its work with bedtools v2.25.0 for me as well.
Thanks yfu!
