### ISSUE TITLE
Coordinate system queries

### ISSUE THREAD

**Issue by cbergman** [JialiUMassWengLab/TEMP#5]
Are the coordinates in the *.insertion.refined.bp.summary file generated by the TEMP_Insertion.sh module on 0-based (i.e. like UCSC BED) or 1-based (like GFF3)?

Also, are the .bed6 input files for TEMP_Insertion.sh and TEMP_Absence.sh expected to be on 0-based or 1-based coordiantes?

**Comment by JialiUMassWengLab** [comment]
Hello Prof. Bergman,

The coordinates from the *.insertion.refined.bp.summary output files are 1-based, including both the interval estimates (the first 3 columns) and the junction estimates (column 9 and 11, if detected). 

The coordinates of the user supplied .bed6 input files, following the UCSC BED format definition, should be 0-based.

Thanks for your interest in TEMP and please let me know if you have any questions. 

Regards,
Jiali

**Comment by cbergman** [comment]
Thanks Jiali, this is just the information we needed.
